<?php

namespace App\Tasks;

final class PhysioTherapy
{
    public static array $items = [
        'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ],
        'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ], 'medication_treatment' => [
            'answers' => 'yes',
            'task' => 'one'
        ],
    ];
}