<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class SocialRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules(): array
    {
        return [
            "collection_date"                                                                                              => 'required',
            "teacher_id"                                                                                                   => 'required',
            "student_id"                                                                                                   => 'required',
            "interaction_with_adults"                                                                                      => 'nullable',
            "age_appropriate_peers"                                                                                                          => 'nullable',
            "interaction_with_younger_children"                                                                            => 'nullable',
            "waiting_for_a_response_from_peers"                                                                            => 'nullable',
            "negotiating_deals"                                                                                            => 'nullable',
            "taking_turns"                                                                                                 => 'nullable',
            "many_individuals_simultaneously"                                                     => 'nullable',
            "ability_to_establish_multiple_friendships"                                                                    => 'nullable',
            "knowing_when_to_persist_or_let_go_of_an_idea"                                                                 => 'nullable',
            "interpreting_facial_expressions_and_voices"                                                                   => 'nullable',
            "understanding_the_rules_of_the_game"                                                                          => 'nullable',
            "expressing_various_appropriate_expressions"                                                                   => 'nullable',
            "receiving_and_giving_gifts"                                                                                   => 'nullable',
            "understanding_sharing"                                                       => 'nullable',
            "participation_in_group_activities"                                                                            => 'nullable',
            "passive_tendencies"                                                                                           => 'nullable',
            "aggressive_tendencies"                                                                                        => 'nullable',
            "responsiveness"                                                                                               => 'nullable',
            "ability_to_handle_being_left_out"                                                                             => 'nullable',
            "expresses_feelings"                                                                                           => 'nullable',
            "identifies_feelings"                                                                                          => 'nullable',
            "explains_feelings"                                                                                            => 'nullable',
            "provides_excuses_or_reasons"                                                                                  => 'nullable',
            "offers_an_opinion_with_support"                                                                               => 'nullable',
            "complains"                                                                                                    => 'nullable',
            "blames_others"                                                                                                => 'nullable',
            "provides_pertinent_information_on_request"                                                                    => 'nullable',
            "ability_to_establish_a_topic"                                                                                 => 'nullable',
            "ability_to_maintain_topic_relevancy"                                                                          => 'nullable',
            "ability_to_change_a_topic_using_signals"                                                                      => 'nullable',
            "ability_to_change_a_topic_using_verbal_means"                                                                 => 'nullable',
            "relevancy_of_information"                                                                                     => 'nullable',
            "ability_to_interrupt_appropriately"                                                                           => 'nullable',
            "ability_to_terminate_the_conversation"                                                                        => 'nullable',
            "ability_to_initiate_a_conversation"                                                                           => 'nullable',
            "the_interest_area"                                             => 'nullable',
            "ability_to_acknowledge_others_in_conversation"                                                                => 'nullable',
            "ability_to_delete"                                                        => 'nullable',
            "ability_to_order_information_appropriately"                                                                   => 'nullable',
            "use_of_pedantic_speech"                                                                                       => 'nullable',
            "ability_to_use_generals_or_specifics"                                                                         => 'nullable',
            "pronoun_use"                                                                                                  => 'nullable',
            "use_of_word_referents"                                                                                        => 'nullable',
            "ability_to_employee"                                                                                          => 'nullable',
            "lie_ambiguous_confusing_information_share"                                                                    => 'nullable',
            "provides_relevant_information"                                                                                => 'nullable',
            "truthfulness_of_information"                                                                                  => 'nullable',
            "ability_to_establish_joint_activity"                                                                          => 'nullable',
            "tendency_to_present_personal_opinions_as_factual"                                                             => 'nullable',
            "requests_clarification_as_needed"                                                                             => 'nullable',
            "spontaneously_provides_additional_information"                                                                => 'nullable',
            "clarification_purposes"                                                => 'nullable',
            "looks_at_speaker_when_called"                                                                                 => 'nullable',
            "delay_of_response"                                                                                            => 'nullable',
            "ability_to_label_information_appropriately"                                                                   => 'nullable',
            "ability_to_describe_objects_appropriately"                                                                    => 'nullable',
            "ability_to_describe_events_appropriately"                                                                     => 'nullable',
            "ability_to_state_facts_appropriately"                                                                         => 'nullable',
            "ability_to_provide_clarification_appropriately"                                                               => 'nullable',
            "makes_polite_requests"                                                                                        => 'nullable',
            "makes_choices"                                                                                                => 'nullable',
            "gives_description_of_an_object_wanted"                                                                        => 'nullable',
            "expresses_a_specific_personal_need"                                                                           => 'nullable',
            "requests_help"                                                                                                => 'nullable',
            "ability_to_request_information_appropriately"                                                                 => 'nullable',
            "ability_to_request_permission_appropriately"                                                                  => 'nullable',
            "ability_to_request_yes_no_responses_appropriately"                                                            => 'nullable',
            "ability_to_use_wh_questions_appropriately"                                                                    => 'nullable',
            "ability_to_request_an_action_of_another_appropriately"                                                        => 'nullable',
            "ability_to_request_clarification_appropriately"                                                               => 'nullable',
            "ability_to_request_attention_appropriately"                                                                   => 'nullable',
            "ability_to_request_help_appropriately"                                                                        => 'nullable',
            "ability_to_use_appropriate_rate_of_speech"                                                                    => 'nullable',
            "ability_to_use_appropriate_tone_of_voice"                                                                     => 'nullable',
            "ability_to_use_appropriate_pitch"                                                                             => 'nullable',
            "ability_to_use_appropriate_loudness"                                                                          => 'nullable',
            "implied_meanings_via_tone_of_voice"                                                     => 'nullable',
            "inflectional_cues"                                                 => 'nullable',
            "ability_to_state_his_opinion_using_appropriate_means"                                                         => 'nullable',
            "ability_to_disagree"                                                                                          => 'nullable',
            "conversation_according_to_person"                                               => 'nullable',
            "ability_to_shift"                                          => 'nullable',
            "conversation_according_to_humor"                                                => 'nullable',
            "ability_to_engage_a_listener_appropriately"                                                                   => 'nullable',
            "ability_to_use_politeness"                                                                                    => 'nullable',
            "appropriateness_to_the_situation"                                                                             => 'nullable',
            "ability_to_recognize_others_moods"                                                                            => 'nullable',
            "ability_to_differentiate_requests_from_demands"                                                               => 'nullable',
            "comprehends_humor"                                                                                            => 'nullable',
            "uses_humor_appropriately"                                                                                     => 'nullable',
            "provides_greetings"                                                                                           => 'nullable',
            "uses_greetings"                                                                                               => 'nullable',
            "another_individual"                                                    => 'nullable',
            "ability_to_solve_problems_affecting_himself"                                                                  => 'nullable',
            "ability_to_solve_problems_affecting_others"                                                                   => 'nullable',
            "ability_to_recognize_problems_affecting_others"                                                               => 'nullable',
            "ability_to_recognize_problems_affecting_himself"                                                              => 'nullable',
            "ability_to_establish_cause_effect"                                                                            => 'nullable',
            "ability_to_use_conflict_resolution"                                                                           => 'nullable',
            "uses_language_to_deceive"                                                                                     => 'nullable',
            "lies"                                                                                                         => 'nullable',
            "to_teacher_requests"                                                         => 'nullable',
            "agenda_appropriately"                                                         => 'nullable',
            "teachers_attention_appropriately"                                                           => 'nullable',
            "ability_to_request_clarification_from_teacher"                                                                => 'nullable',
            "ability_to_participate_in_classroom_discussions"                                                              => 'nullable',
            "ability_to_interact_with_classroom_peers"                                                                     => 'nullable',
            "ability_to_paraphrase_text"                                                                                   => 'nullable',
            "ability_to_summarize_a_story_providing_key_information"                                                       => 'nullable',
            "requiring_inferential_reasoning"                                              => 'nullable',
            "ability_to_recognize_personal_space_boundaries"                                                               => 'nullable',
            "ability_to_touch_appropriatel"                                                                                => 'nullable',
            "comprehends_facial_expression"                                                                                => 'nullable',
            "comprehends_eye_gaze"                                                                                         => 'nullable',
            "comprehends_gestures"                                                                                         => 'nullable',
            "comprehends_body_language"                                                                                    => 'nullable',
            "ability_to_use_facial_expression"                                                                             => 'nullable',
            "ability_to_use_eye_gaze"                                                                                      => 'nullable',
            "ability_to_use_gestures"                                                                                      => 'nullable',
            "ability_to_use_body_language"                                                                                 => 'nullable',
            "ability_to_use_eye_contact"                                                                                   => 'nullable',
            "ability_to_recognize_anothers_viewpoints"                                                                     => 'nullable',
            "ability_to_recognize_anothers_interests"                                                                      => 'nullable',
            "ability_to_recognize_anothers_feelings"                                                                       => 'nullable',
            "concern_for_anothers_problems"                                                         => 'nullable',
            "gives_directions_to_play_a_game"                                                                              => 'nullable',
            "gives_directions_to_make_something"                                                                           => 'nullable',
            "changes_the_style" => 'nullable',
            "ability_to_recognize_personal_emotional_states"                                                               => 'nullable',
            "ability_to_recognize_emotional_states_in_others"                                                              => 'nullable',
            "ability_to_express_personal_emotional_state"                                                                  => 'nullable',
            "perfectionist_quality"                                                                                        => 'nullable',
            "ability_to_use_appropriate_self_control"                                                                      => 'nullable',
            "ability_to_lose_a_game_graciously"                                                                            => 'nullable',
            "degree_of_anxiety_in_social_settings"                                                                         => 'nullable',
        ];
    }
}
