<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class TripRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules(): array
    {
        return [
            "collection_date"   => 'nullable',
            "teacher_id"        => 'nullable',
            'bath'              => 'nullable',
            'bath_secondary' => 'nullable',
            'wearing_cloth' => 'nullable',
            'wearing_cloth_secondary' => 'nullable',
            'wrooming' => 'nullable',
            'wrooming_secondary' => 'nullable',
            'do_toilet' => 'nullable',
            'do_toilet_secondary' => 'nullable',
            'eating_healthy_food' => 'nullable',
            'eating_healthy_food_secondary' => 'nullable',
            'wakeup_from_bed' => 'nullable',
            'wakeup_from_bed_secondary' => 'nullable',
            'get_up_from_the_chair' => 'nullable',
            'get_up_from_the_chair_secondary' => 'nullable',
            'walk' => 'nullable',
            'walk_secondary' => 'nullable',

            'taking_trip_materials_and_preparation' => 'nullable',
            'taking_trip_materials_and_preparation_secondary' => 'nullable',
            'whether_the_trainee_has_been_contacted' => 'nullable',
            'whether_the_trainee_has_been_contacted_secondary' => 'nullable',
            'communicate_with_other_members_of_the_team' => 'nullable',
            'communicate_with_other_members_of_the_team_secondary' => 'nullable',
            'where_visits' => 'nullable',
            'where_visits_secondary' => 'nullable',
            'who_were_driving_cars_or_other_assistants' => 'nullable',
            'who_were_driving_cars_or_other_assistants_secondary' => 'nullable',
            'overall_tour_like' => 'nullable',
            'overall_tour_like_secondary' => 'nullable',
            'this_trip' => 'nullable',
            'this_trip_secondary' => 'nullable',
            'tour_presented_and_managed_professionally' => 'nullable',
            'tour_presented_and_managed_professionally_secondary' => 'nullable',
            'teacher_went_alone_or_in_the_team' => 'nullable',
            'teacher_went_alone_or_in_the_team_secondary' => 'nullable',
            'trip_description' => 'nullable',

            'home_environment' => 'nullable',
            'home_environment_secondary' => 'nullable',
            'do_need_separate_room' => 'nullable',
            'do_need_separate_room_secondary' => 'nullable',
            'separate_bed' => 'nullable',
            'separate_bed_secondary' => 'nullable',
            'for_cloth_separate_elmira' => 'nullable',
            'for_cloth_separate_elmira_secondary' => 'nullable',
            'separate_place_for_change_cloth' => 'nullable',
            'separate_place_for_change_cloth_secondary' => 'nullable',
            'attach_bathroom' => 'nullable',
            'attach_bathroom_secondary' => 'nullable',
            'attach_balcony' => 'nullable',
            'attach_balcony_secondary' => 'nullable',
            'separate_reading_environment' => 'nullable',
            'separate_reading_environment_secondary' => 'nullable',

            'large_lock_on_the_outer_door' => 'nullable',
            'large_lock_on_the_outer_door_secondary' => 'nullable',
            'front_door_leaks' => 'nullable',
            'front_door_leaks_secondary' => 'nullable',
            'lock_windows' => 'nullable',
            'lock_windows_secondary' => 'nullable',
            'alarm_system' => 'nullable',
            'alarm_system_secondary' => 'nullable',
            'walk_or_other_obstacles' => 'nullable',
            'walk_or_other_obstacles_secondary' => 'nullable',
            'if_no_room_alternative_solution' => 'nullable',

            'using_bed_or_chair_are_easy' => 'nullable',
            'using_bed_or_chair_are_easy_secondary' => 'nullable',
            'correct_height_chair' => 'nullable',
            'correct_height_chair_secondary' => 'nullable',
            'up_down_form_bed_easy' => 'nullable',
            'up_down_form_bed_easy_secondary' => 'nullable',

            'easily_lights_on_and_off' => 'nullable',
            'easily_lights_on_and_off_secondary' => 'nullable',
            'enough_light_study_area' => 'nullable',
            'enough_light_study_area_secondary' => 'nullable',
            'night_lights_passage_way' => 'nullable',
            'night_lights_passage_way_secondary' => 'nullable',

            'tap_the_basin_within_reach' => 'nullable',
            'tap_the_basin_within_reach_secondary' => 'nullable',
            'plate_rack_within_reach' => 'nullable',
            'plate_rack_within_reach_secondary' => 'nullable',
            'items_are_within_reach' => 'nullable',
            'items_are_within_reach_secondary' => 'nullable',
            'cooking_items_within_reach' => 'nullable',
            'cooking_items_within_reach_secondary' => 'nullable',
            'store_is_easily_accessible' => 'nullable',
            'store_is_easily_accessible_secondary' => 'nullable',
            'refrigerator_within_reach' => 'nullable',
            'refrigerator_within_reach_secondary' => 'nullable',
            'something_on_stove' => 'nullable',
            'something_on_stove_secondary' => 'nullable',
            'enough_light' => 'nullable',
            'enough_light_secondary' => 'nullable',

            'stand_for_support_in_bathroom' => 'nullable',
            'stand_for_support_in_bathroom_secondary' => 'nullable',
            'slippery_insulated_bathroom' => 'nullable',
            'slippery_insulated_bathroom_secondary' => 'nullable',
            'hand_shower_for_bath' => 'nullable',
            'hand_shower_for_bath_secondary' => 'nullable',
            'soap_shampoo_brach_within_rich' => 'nullable',
            'soap_shampoo_brach_within_rich_secondary' => 'nullable',

            'slippery_insulated_floor' => 'nullable',
            'slippery_insulated_floor_secondary' => 'nullable',
            'whether_there_is_any_looseness_in_anger_or_papos' => 'nullable',
            'whether_there_is_any_looseness_in_anger_or_papos_secondary' => 'nullable',

            'telephone_uses_or_video_call' => 'nullable',
            'telephone_uses_or_video_call_secondary' => 'nullable',
            'money_manage_or_uses' => 'nullable',
            'money_manage_or_uses_secondary' => 'nullable',
            'personal_or_favorite_things_buy' => 'nullable',
            'personal_or_favorite_things_buy_secondary' => 'nullable',
            'transportation_uses' => 'nullable',
            'transportation_uses_secondary' => 'nullable',
            'doing_laundry_or_separate_dirty_cloth_or_dying' => 'nullable',
            'doing_laundry_or_separate_dirty_cloth_or_dying_secondary' => 'nullable',
            'cloth_fold_and_put_in_drawer' => 'nullable',
            'cloth_fold_and_put_in_drawer_secondary' => 'nullable',
            'working_at_home_or_toy_or_playground_clean_up' => 'nullable',
            'working_at_home_or_toy_or_playground_clean_up_secondary' => 'nullable',
            'cooking_food_or_eat_himself' => 'nullable',
            'cooking_food_or_eat_himself_secondary' => 'nullable',
            'cutting_vegetable_or_arrange_separately' => 'nullable',
            'cutting_vegetable_or_arrange_separately_secondary' => 'nullable',

            'security' => 'nullable',
            'security_secondary' => 'nullable',
            'comfortable_arrangements' => 'nullable',
            'comfortable_arrangements_secondary' => 'nullable',
            'close_friend_or_relative' => 'nullable',
            'close_friend_or_relative_secondary' => 'nullable',

            'free_from_noise_and_obstruction' => 'nullable',
            'free_from_noise_and_obstruction_secondary' => 'nullable',
            'handles_on_both_sides_step' => 'nullable',
            'handles_on_both_sides_step_secondary' => 'nullable',
            'clearly_marked' => 'nullable',
            'clearly_marked_secondary' => 'nullable',
            'other_if_any' => 'nullable',
            'other_if_any_secondary' => 'nullable',
            'enter_the_details' => 'nullable',

            'wakeup_morning' => 'nullable',
            'wakeup_morning_secondary' => 'nullable',
            'wakeup_morning_time' => 'nullable',
            'wakeup_morning_time_secondary' => 'nullable',
            'bed_arrangement' => 'nullable',
            'bed_arrangement_secondary' => 'nullable',
            'bed_arrangement_time' => 'nullable',
            'bed_arrangement_time_secondary' => 'nullable',
            'teeth_brash' => 'nullable',
            'teeth_brash_secondary' => 'nullable',
            'teeth_brash_time' => 'nullable',
            'teeth_brash_time_secondary' => 'nullable',
            'hand_face_washing' => 'nullable',
            'hand_face_washing_secondary' => 'nullable',
            'hand_face_washing_time' => 'nullable',
            'hand_face_washing_time_secondary' => 'nullable',
            'changing_cloth' => 'nullable',
            'changing_cloth_secondary' => 'nullable',
            'changing_cloth_time' => 'nullable',
            'changing_cloth_time_secondary' => 'nullable',
            'hair_combing' => 'nullable',
            'hair_combing_secondary' => 'nullable',
            'hair_combing_time' => 'nullable',
            'hair_combing_time_secondary' => 'nullable',
            'snakes_cooking_eat_or_in_table' => 'nullable',
            'snakes_cooking_eat_or_in_table_secondary' => 'nullable',
            'snakes_cooking_eat_or_in_table_time' => 'nullable',
            'snakes_cooking_eat_or_in_table_time_secondary' => 'nullable',
            'cleaning_pleat_or_glass_or_put_in_wash_place' => 'nullable',
            'cleaning_pleat_or_glass_or_put_in_wash_place_secondary' => 'nullable',
            'cleaning_pleat_or_glass_or_put_in_wash_place_time' => 'nullable',
            'cleaning_pleat_or_glass_or_put_in_wash_place_time_secondary' => 'nullable',
            'clean_up_table' => 'nullable',
            'clean_up_table_secondary' => 'nullable',
            'clean_up_table_time' => 'nullable',
            'clean_up_table_time_secondary' => 'nullable',

            'reading' => 'nullable',
            'reading_secondary' => 'nullable',
            'reading_time' => 'nullable',
            'reading_time_secondary' => 'nullable',
            'hand_writing' => 'nullable',
            'hand_writing_secondary' => 'nullable',
            'hand_writing_time' => 'nullable',
            'hand_writing_time_secondary' => 'nullable',
            'drawing_picture' => 'nullable',
            'drawing_picture_secondary' => 'nullable',
            'drawing_picture_time' => 'nullable',
            'drawing_picture_time_secondary' => 'nullable',
            'reading_paper' => 'nullable',
            'reading_paper_secondary' => 'nullable',
            'reading_paper_time' => 'nullable',
            'reading_paper_time_secondary' => 'nullable',
            'listening_song' => 'nullable',
            'listening_song_secondary' => 'nullable',
            'listening_song_time' => 'nullable',
            'listening_song_time_secondary' => 'nullable',
            'computer_practice' => 'nullable',
            'computer_practice_secondary' => 'nullable',
            'computer_practice_time' => 'nullable',
            'computer_practice_time_secondary' => 'nullable',

            'list_for_marketing' => 'nullable',
            'list_for_marketing_secondary' => 'nullable',
            'list_for_marketing_time' => 'nullable',
            'list_for_marketing_time_secondary' => 'nullable',
            'marketing_with_mother_and_father' => 'nullable',
            'marketing_with_mother_and_father_secondary' => 'nullable',
            'marketing_with_mother_and_father_time' => 'nullable',
            'marketing_with_mother_and_father_time_secondary' => 'nullable',
            'helping_mother_for_cutting_and_cooking_food' => 'nullable',
            'helping_mother_for_cutting_and_cooking_food_secondary' => 'nullable',
            'helping_mother_for_cutting_and_cooking_food_time' => 'nullable',
            'helping_mother_for_cutting_and_cooking_food_time_secondary' => 'nullable',
            'creating_menu_or_recognize_food_using_image' => 'nullable',
            'creating_menu_or_recognize_food_using_image_secondary' => 'nullable',
            'creating_menu_or_recognize_food_using_image_time' => 'nullable',
            'creating_menu_or_recognize_food_using_image_time_secondary' => 'nullable',

            'washing_cloth_and_drying' => 'nullable',
            'washing_cloth_and_drying_secondary' => 'nullable',
            'washing_cloth_and_drying_time' => 'nullable',
            'washing_cloth_and_drying_time_secondary' => 'nullable',
            'clean_up_himself_room' => 'nullable',
            'clean_up_himself_room_secondary' => 'nullable',
            'clean_up_himself_room_time' => 'nullable',
            'clean_up_himself_room_time_secondary' => 'nullable',
            'folding_cloth' => 'nullable',
            'folding_cloth_secondary' => 'nullable',
            'folding_cloth_time' => 'nullable',
            'folding_cloth_time_secondary' => 'nullable',
            'tidy_wardrobe_or_cotton_drawer' => 'nullable',
            'tidy_wardrobe_or_cotton_drawer_secondary' => 'nullable',
            'tidy_wardrobe_or_cotton_drawer_time' => 'nullable',
            'tidy_wardrobe_or_cotton_drawer_time_secondary' => 'nullable',
            'iron_cloth' => 'nullable',
            'iron_cloth_secondary' => 'nullable',
            'iron_cloth_time' => 'nullable',
            'iron_cloth_time_secondary' => 'nullable',
            'cutting_nails' => 'nullable',
            'cutting_nails_secondary' => 'nullable',
            'cutting_nails_time' => 'nullable',
            'cutting_nails_time_secondary' => 'nullable',
            'hair_cutting' => 'nullable',
            'hair_cutting_secondary' => 'nullable',
            'hair_cutting_time' => 'nullable',
            'hair_cutting_time_secondary' => 'nullable',
            'shave' => 'nullable',
            'shave_secondary' => 'nullable',
            'shave_time' => 'nullable',
            'shave_time_secondary' => 'nullable',

            'give_plate_glass_on_the_table_will_help' => 'nullable',
            'give_plate_glass_on_the_table_will_help_secondary' => 'nullable',
            'give_plate_glass_on_the_table_will_help_time' => 'nullable',
            'give_plate_glass_on_the_table_will_help_time_secondary' => 'nullable',
            'give_water_in_glass' => 'nullable',
            'give_water_in_glass_secondary' => 'nullable',
            'give_water_in_glass_time' => 'nullable',
            'give_water_in_glass_time_secondary' => 'nullable',
            'bring_food_from_the_kitchen_to_the_table' => 'nullable',
            'bring_food_from_the_kitchen_to_the_table_secondary' => 'nullable',
            'bring_food_from_the_kitchen_to_the_table_time' => 'nullable',
            'bring_food_from_the_kitchen_to_the_table_time_secondary' => 'nullable',
            'sit_on_the_table_or_mat_and_eat_with_everyone' => 'nullable',
            'sit_on_the_table_or_mat_and_eat_with_everyone_secondary' => 'nullable',
            'sit_on_the_table_or_mat_and_eat_with_everyone_time' => 'nullable',
            'sit_on_the_table_or_mat_and_eat_with_everyone_time_secondary' => 'nullable',
            'eat_with_your_own_hands_or_spoon' => 'nullable',
            'eat_with_your_own_hands_or_spoon_secondary' => 'nullable',
            'eat_with_your_own_hands_or_spoon_time' => 'nullable',
            'eat_with_your_own_hands_or_spoon_time_secondary' => 'nullable',
            'table_or_mat_will_help_clean' => 'nullable',
            'table_or_mat_will_help_clean_secondary' => 'nullable',
            'table_or_mat_will_help_clean_time' => 'nullable',
            'table_or_mat_will_help_clean_time_secondary' => 'nullable',

            'rest_in_bed' => 'nullable',
            'rest_in_bed_secondary' => 'nullable',
            'rest_in_bed_time' => 'nullable',
            'rest_in_bed_time_secondary' => 'nullable',
            'reading_story_book' => 'nullable',
            'reading_story_book_secondary' => 'nullable',
            'reading_story_book_time' => 'nullable',
            'reading_story_book_time_secondary' => 'nullable',
            'rest_time_listening_song' => 'nullable',
            'rest_time_listening_song_secondary' => 'nullable',
            'rest_time_listening_song_time' => 'nullable',
            'rest_time_listening_song_time_secondary' => 'nullable',
            'playing_video_game' => 'nullable',
            'playing_video_game_secondary' => 'nullable',
            'playing_video_game_time' => 'nullable',
            'playing_video_game_time_secondary' => 'nullable',

            'going_for_walk' => 'nullable',
            'going_for_walk_secondary' => 'nullable',
            'going_for_walk_time' => 'nullable',
            'going_for_walk_time_secondary' => 'nullable',
            'water_in_tub' => 'nullable',
            'water_in_tub_secondary' => 'nullable',
            'water_in_tub_time' => 'nullable',
            'water_in_tub_time_secondary' => 'nullable',
            'going_to_play_in_roof_or_playground' => 'nullable',
            'going_to_play_in_roof_or_playground_secondary' => 'nullable',
            'going_to_play_in_roof_or_playground_time' => 'nullable',
            'going_to_play_in_roof_or_playground_time_secondary' => 'nullable',
            'play_favorite_game' => 'nullable',
            'play_favorite_game_secondary' => 'nullable',
            'play_favorite_game_time' => 'nullable',
            'play_favorite_game_time_secondary' => 'nullable',
            'visiting_house_or_favorite_place_or_shopping' => 'nullable',
            'visiting_house_or_favorite_place_or_shopping_secondary' => 'nullable',
            'visiting_house_or_favorite_place_or_shopping_time' => 'nullable',
            'visiting_house_or_favorite_place_or_shopping_time_secondary' => 'nullable',

            'Make_sherbet_or_tea_or_snakes' => 'nullable',
            'Make_sherbet_or_tea_or_snakes_secondary' => 'nullable',
            'Make_sherbet_or_tea_or_snakes_time' => 'nullable',
            'Make_sherbet_or_tea_or_snakes_time_secondary' => 'nullable',
            'guest_reception' => 'nullable',
            'guest_reception_secondary' => 'nullable',
            'guest_reception_time' => 'nullable',
            'guest_reception_time_secondary' => 'nullable',
            'spending_time_with_brother_sister' => 'nullable',
            'spending_time_with_brother_sister_secondary' => 'nullable',
            'spending_time_with_brother_sister_time' => 'nullable',
            'spending_time_with_brother_sister_time_secondary' => 'nullable',

            'reading_book_and_hand_writing' => 'nullable',
            'reading_book_and_hand_writing_secondary' => 'nullable',
            'reading_book_and_hand_writing_time' => 'nullable',
            'reading_book_and_hand_writing_time_secondary' => 'nullable',
            'constructive_game' => 'nullable',
            'constructive_game_secondary' => 'nullable',
            'constructive_game_time' => 'nullable',
            'constructive_game_time_secondary' => 'nullable',
            'constructive_work_computer_practice' => 'nullable',
            'constructive_work_computer_practice_secondary' => 'nullable',
            'constructive_work_computer_practice_time' => 'nullable',
            'constructive_work_computer_practice_time_secondary' => 'nullable',
            'home_work' => 'nullable',
            'home_work_secondary' => 'nullable',
            'home_work_time' => 'nullable',
            'home_work_time_secondary' => 'nullable',
            'packing_the_bag_for_the_next_day' => 'nullable',
            'packing_the_bag_for_the_next_day_secondary' => 'nullable',
            'packing_the_bag_for_the_next_day_time' => 'nullable',
            'packing_the_bag_for_the_next_day_time_secondary' => 'nullable',
            'watching_tv' => 'nullable',
            'watching_tv_secondary' => 'nullable',
            'watching_tv_time' => 'nullable',
            'watching_tv_time_secondary' => 'nullable',
            'dairy_writing' => 'nullable',
            'dairy_writing_secondary' => 'nullable',
            'dairy_writing_time' => 'nullable',
            'dairy_writing_time_secondary' => 'nullable',


            'night_give_plate_glass_on_the_table_will_help' => 'nullable',
            'night_give_plate_glass_on_the_table_will_help_secondary' => 'nullable',
            'night_give_plate_glass_on_the_table_will_help_time' => 'nullable',
            'night_give_plate_glass_on_the_table_will_help_time_secondary' => 'nullable',
            'night_Give_water_in_glass' => 'nullable',
            'night_Give_water_in_glass_secondary' => 'nullable',
            'night_Give_water_in_glass_time' => 'nullable',
            'night_Give_water_in_glass_time_secondary' => 'nullable',
            'night_bring_food_from_the_kitchen_to_the_table' => 'nullable',
            'night_bring_food_from_the_kitchen_to_the_table_secondary' => 'nullable',
            'night_bring_food_from_the_kitchen_to_the_table_time' => 'nullable',
            'night_bring_food_from_the_kitchen_to_the_table_time_secondary' => 'nullable',
            'night_wash_hands_with_soap_before_and_after_eating' => 'nullable',
            'night_sit_on_table_or_mat_and_eat_with_everyone' => 'nullable',
            'night_sit_on_table_or_mat_and_eat_with_everyone_secondary' => 'nullable',
            'night_sit_on_table_or_mat_and_eat_with_everyone_time' => 'nullable',
            'night_sit_on_table_or_mat_and_eat_with_everyone_time_secondary' => 'nullable',
            'night_eat_with_your'   => 'nullable',
            'night_eat_with_your_own_hands_or_spoon_secondary' => 'nullable',
            'night_eat_with_your_own_hands_or_spoon_time' => 'nullable',
            'night_eat_with_your_own_hands_or_spoon_time_secondary' => 'nullable',

            'night_eating_medicine' => 'nullable',
            'night_eating_medicine_secondary' => 'nullable',
            'night_eating_medicine_time' => 'nullable',
            'night_eating_medicine_time_secondary' => 'nullable',
            'night_teeth_brash' => 'nullable',
            'night_teeth_brash_secondary' => 'nullable',
            'night_teeth_brash_time' => 'nullable',
            'night_teeth_brash_time_secondary' => 'nullable',
            'night_changing_cloth' => 'nullable',
            'night_changing_cloth_secondary' => 'nullable',
            'night_changing_cloth_time' => 'nullable',
            'night_changing_cloth_time_secondary' => 'nullable',
            'put_to_bed' => 'nullable',
            'put_to_bed_secondary' => 'nullable',
            'put_to_bed_time' => 'nullable',
            'put_to_bed_time_secondary' => 'nullable',
            'hanging_mosquito_nets' => 'nullable',
            'hanging_mosquito_nets_secondary' => 'nullable',
            'hanging_mosquito_nets_time' => 'nullable',
            'hanging_mosquito_nets_time_secondary' => 'nullable',
            'turn_off_the_lights_and_go_to_bed' => 'nullable',
            'turn_off_the_lights_and_go_to_bed_secondary' => 'nullable',
            'turn_off_the_lights_and_go_to_bed_time' => 'nullable',
            'turn_off_the_lights_and_go_to_bed_time_secondary' => 'nullable',
            'turn_off_the_lights_and_go_to_bed_time_secondary' => 'nullable',
            'turn_off_the_lights_and_go_to_bed_time_secondary' => 'nullable',

            'special_educator_team' => 'nullable',
            'special_educator_team_name' => 'nullable',
            'guardian_img' => 'nullable',
            'guardian_name' => 'nullable',
            'note_if_any' => 'nullable',

            'signature_teacher' => 'nullable',
            'signature_teacher_name_or_designation' => 'nullable',
            'supervisor_signature' => 'nullable',
            'supervisor_signature_name_or_designation' => 'nullable',

        ];
    }
}
