<?php

namespace App\Utility;

final class SocialCommunication
{
    public static array $columnCollections = [
        'pragmatic_objective'            => [
            'interaction_with_adults',
            'age_appropriate_peers',
            'interaction_with_younger_children',
            'waiting_for_a_response_from_peers',
            'negotiating_deals',
            'taking_turns',
            'many_individuals_simultaneously',
            'ability_to_establish_multiple_friendships',
            'knowing_when_to_persist_or_let_go_of_an_idea',
            'interpreting_facial_expressions_and_voices',
            'understanding_the_rules_of_the_game',
            'expressing_various_appropriate_expressions',
            'receiving_and_giving_gifts',
            'understanding_sharing',
            'participation_in_group_activities',
            'passive_tendencies',
            'aggressive_tendencies',
            'responsiveness',
            'ability_to_handle_being_left_out',
        ],
        'personal'            => [
            'expresses_feelings',
            'identifies_feelings',
            'explains_feelings',
            'provides_excuses_or_reasons',
            'offers_an_opinion_with_support',
            'complains',
            'blames_others',
            'provides_pertinent_information_on_request',
        ],
        'topic_maintenance'            => [
            'ability_to_establish_a_topic',
            'ability_to_maintain_topic_relevancy',
            'ability_to_change_a_topic_using_signals',
            'ability_to_change_a_topic_using_verbal_means',
            'relevancy_of_information',
            'ability_to_interrupt_appropriately',
            'ability_to_terminate_the_conversation',
        ],
        'conversational_structure'            => [
            'ability_to_initiate_a_conversation',
            'the_interest_area',
            'ability_to_acknowledge_others_in_conversation',
            'ability_to_delete',
            'ability_to_order_information_appropriately',
            'use_of_pedantic_speech',
        ],
        'word_structure'            => [
            'ability_to_use_generals_or_specifics',
            'pronoun_use',
            'use_of_word_referents',
            'ability_to_employee',
        ],
        'manner_effectiveness'            => [
            'lie_ambiguous_confusing_information_share',
            'provides_relevant_information',
            'truthfulness_of_information',
            'ability_to_establish_joint_activity',
            'tendency_to_present_personal_opinions_as_factual',
        ],
        'repair_structures'            => [
            'requests_clarification_as_needed',
            'spontaneously_provides_additional_information',
            'clarification_purposes',
        ],
        'responsiveness'            => [
            'looks_at_speaker_when_called',
            'delay_of_response',
            'ability_to_label_information_appropriately',
            'ability_to_describe_objects_appropriately',
            'ability_to_describe_events_appropriately',
            'ability_to_state_facts_appropriately',
            'ability_to_provide_clarification_appropriately',
        ],
        'instrumental_states_needs'            => [
            'makes_polite_requests',
            'makes_choices',
            'gives_description_of_an_object_wanted',
            'expresses_a_specific_personal_need',
            'requests_help',
        ],

        'requesting'            => [
            'ability_to_request_information_appropriately',
            'ability_to_request_permission_appropriately',
            'ability_to_request_yes_no_responses_appropriately',
            'ability_to_use_wh_questions_appropriately',
            'ability_to_request_an_action_of_another_appropriately',
            'ability_to_request_clarification_appropriately',
            'ability_to_request_attention_appropriately',
            'ability_to_request_help_appropriately',

        ],
        'prosody'            => [
            'ability_to_use_appropriate_rate_of_speech',
            'ability_to_use_appropriate_tone_of_voice',
            'ability_to_use_appropriate_pitch',
            'ability_to_use_appropriate_loudness',
            'implied_meanings_via_tone_of_voice',
            'inflectional_cues',
        ],
        'protests'            => [
            'ability_to_state_his_opinion_using_appropriate_means',
            'ability_to_disagree',
        ],
        'style_of_Conversation'            => [
            'conversation_according_to_person',
            'ability_to_shift',
            'conversation_according_to_humor',
            'ability_to_engage_a_listener_appropriately',
            'ability_to_use_politeness',
            'appropriateness_to_the_situation',
            'ability_to_recognize_others_moods',
            'ability_to_differentiate_requests_from_demands'
        ],
        'humor'            => [
            'comprehends_humor',
            'uses_humor_appropriately',
        ],
        'greetings_acknowledgements'            => [
            'provides_greetings',
            'uses_greetings',
            'another_individual',
        ],
        'problem_solving'            => [
            'ability_to_solve_problems_affecting_himself',
            'ability_to_solve_problems_affecting_others',
            'ability_to_recognize_problems_affecting_others',
            'ability_to_recognize_problems_affecting_himself',
            'ability_to_establish_cause_effect',
            'ability_to_use_conflict_resolution',
        ],
        'deceit'            => [
            'uses_language_to_deceive',
            'lies',
        ],
        'academy_communication'            => [
            'to_teacher_requests',
            'agenda_appropriately',
            'teachers_attention_appropriately',
            'ability_to_request_clarification_from_teacher',
            'ability_to_participate_in_classroom_discussions',
            'ability_to_interact_with_classroom_peers',
            'ability_to_paraphrase_text',
            'ability_to_summarize_a_story_providing_key_information',
            'requiring_inferential_reasoning',
        ],
        'nonverbal_communication'           => [
            'ability_to_recognize_personal_space_boundaries',
            'ability_to_touch_appropriatel',
            'comprehends_facial_expression',
            'comprehends_eye_gaze',
            'comprehends_gestures',
            'comprehends_body_language',
            'ability_to_use_facial_expression',
            'ability_to_use_eye_gaze',
            'ability_to_use_gestures',
            'ability_to_use_body_language',
            'ability_to_use_eye_contact',
        ],
        'perspective_taking'            => [
            'ability_to_recognize_anothers_viewpoints',
            'ability_to_recognize_anothers_interests',
            'ability_to_recognize_anothers_feelings',
            'concern_for_anothers_problems',
        ],
        'regulatory_gives_commands'            => [
            'gives_directions_to_play_a_game',
            'gives_directions_to_make_something',
            'changes_the_style',
        ],
        'social_emotional'            => [
            'ability_to_recognize_personal_emotional_states',
            'ability_to_recognize_emotional_states_in_others',
            'ability_to_express_personal_emotional_state',
            'perfectionist_quality',
            'ability_to_use_appropriate_self_control',
            'ability_to_lose_a_game_graciously',
            'degree_of_anxiety_in_social_settings',
        ],

    ];
}
