<?php

namespace App\Utility;

final class TripReport
{
    const SELFDOING = 'একা করছে';
    const LITTLEHELP = 'সামান্য সাহায্যে';
    const HUGEHELP = 'বেশী সাহায্যে';

    public static array $do = [
        self::SELFDOING => 'একা করছে',
        self::LITTLEHELP => 'সামান্য সাহায্যে',
        self::HUGEHELP => 'বেশী সাহায্যে',
    ];


    // ট্রিপ উপকরণ ও প্রস্তুতি গ্রহণ
    const BAD = 'খারাপ';
    const MEDIUM = 'মোটামুটি';
    const FINE = 'ভালো';
    const VERYFINE = 'খুব ভালো';


    public static array $observation = [
        self::BAD => 'খারাপ',
        self::MEDIUM => 'মোটামুটি',
        self::FINE => 'ভালো',
        self::VERYFINE => 'খুব ভালো',
    ];

    // এই ট্রিপ
    const EXPECTATION = 'প্রত্যাশা পূরণ করছে';
    const FAIL = ' ব্যর্থ হয়েছে ';
    const BETTER = 'প্রত্যাশার চেয়ে ভালো হয়েছে';


    public static array $expectation = [
        self::EXPECTATION => 'প্রত্যাশা পূরণ করছে',
        self::FAIL => ' ব্যর্থ হয়েছে ',
        self::BETTER => 'প্রত্যাশার চেয়ে ভালো হয়েছে',
    ];

    const ALONE = 'একা';
    const NOTALONE = ' দলে ';


    public static array $situation = [
        self::ALONE => 'একা',
        self::NOTALONE => 'দলে',
    ];

    const NOPROBLEM = 'সমস্যা নেই';
    const CHANGE = ' পরিবর্তন দরকার';


    public static array $change = [

        self::NOPROBLEM => 'সমস্যা নেই',
        self::CHANGE => 'পরিবর্তন দরকার',
    ];


    const HELP1 = 'পুরপুরি সাহায্য নিয়ে করা';
    const HELP2 = ' আংশিক সাহায্য নিয়ে করা';
    const HELP3 = 'ছবির মাধ্যমে/দেখে কাজ করা';
    const HELP4 = ' মৌখিক নির্দেশে কাজ করা';
    const HELP5 = ' নিজে থেকে কাজ করা';



    public static array $help = [

        self::HELP1 => 'পুরপুরি সাহায্য নিয়ে করা',
        self::HELP2 => 'আংশিক সাহায্য নিয়ে করা',
        self::HELP3 => 'ছবির মাধ্যমে/দেখে কাজ করা',
        self::HELP4 => 'মৌখিক নির্দেশে কাজ করা',
        self::HELP5 => 'নিজে থেকে কাজ করা',
    ];

    public static array $columnCollections = [
        'activities_of_daily_living' => [
            'bath',
            'bath_secondary',
            'wearing_cloth',
            'wearing_cloth_secondary',
            'wrooming',
            'wrooming_secondary',
            'do_toilet',
            'do_toilet_secondary',
            'eating_healthy_food',
            'eating_healthy_food_secondary',
            'wakeup_from_bed',
            'wakeup_from_bed_secondary',
            'get_up_from_the_chair',
            'get_up_from_the_chair_secondary',
            'walk',
            'walk_secondary',
        ],
        'only_for_staff'             => [
            'taking_trip_materials_and_preparation',
            'taking_trip_materials_and_preparation_secondary',
            'whether_the_trainee_has_been_contacted',
            'whether_the_trainee_has_been_contacted_secondary',
            'communicate_with_other_members_of_the_team',
            'communicate_with_other_members_of_the_team_secondary',
            'where_visits',
            'where_visits_secondary',
            'who_were_driving_cars_or_other_assistants',
            'who_were_driving_cars_or_other_assistants_secondary',
            'overall_tour_like',
            'overall_tour_like_secondary',
            'this_trip',
            'this_trip_secondary',
            'tour_presented_and_managed_professionally',
            'tour_presented_and_managed_professionally_secondary',
            'teacher_went_alone_or_in_the_team',
            'teacher_went_alone_or_in_the_team_secondary',
            'trip_description',
        ],
        'activities' => [
            'home_environment',
            'home_environment_secondary',
            'do_need_separate_room',
            'do_need_separate_room_secondary',
            'separate_bed',
            'separate_bed_secondary',
            'for_cloth_separate_elmira',
            'for_cloth_separate_elmira_secondary',
            'separate_place_for_change_cloth',
            'separate_place_for_change_cloth_secondary',
            'attach_bathroom',
            'attach_bathroom_secondary',
            'attach_balcony',
            'attach_balcony_secondary',
            'separate_reading_environment',
            'separate_reading_environment_secondary',
        ],
        'security_safety' => [
            'large_lock_on_the_outer_door',
            'large_lock_on_the_outer_door_secondary',
            'front_door_leaks',
            'front_door_leaks_secondary',
            'lock_windows',
            'lock_windows_secondary',
            'alarm_system',
            'alarm_system_secondary',
            'walk_or_other_obstacles',
            'walk_or_other_obstacles_secondary',
            'if_no_room_alternative_solution',
        ],
        'equipment' => [
            'using_bed_or_chair_are_easy',
            'using_bed_or_chair_are_easy_secondary',
            'correct_height_chair',
            'correct_height_chair_secondary',
            'up_down_form_bed_easy',
            'up_down_form_bed_easy_secondary',
        ],
        'light' => [
            'easily_lights_on_and_off',
            'easily_lights_on_and_off_secondary',
            'enough_light_study_area',
            'enough_light_study_area_secondary',
            'night_lights_passage_way',
            'night_lights_passage_way_secondary',
        ],
        'kitchen' => [
            'tap_the_basin_within_reach',
            'tap_the_basin_within_reach_secondary',
            'plate_rack_within_reach',
            'plate_rack_within_reach_secondary',
            'items_are_within_reach',
            'items_are_within_reach_secondary',
            'cooking_items_within_reach',
            'cooking_items_within_reach_secondary',
            'store_is_easily_accessible',
            'store_is_easily_accessible_secondary',
            'refrigerator_within_reach',
            'refrigerator_within_reach_secondary',
            'something_on_stove',
            'something_on_stove_secondary',
            'enough_light',
            'enough_light_secondary',
        ],
        'bathroom' => [
            'stand_for_support_in_bathroom',
            'stand_for_support_in_bathroom_secondary',
            'slippery_insulated_bathroom',
            'slippery_insulated_bathroom_secondary',
            'hand_shower_for_bath',
            'hand_shower_for_bath_secondary',
            'soap_shampoo_brach_within_rich',
            'soap_shampoo_brach_within_rich_secondary',
        ],
        'floor' => [
            'slippery_insulated_floor',
            'slippery_insulated_floor_secondary',
            'whether_there_is_any_looseness_in_anger_or_papos',
            'whether_there_is_any_looseness_in_anger_or_papos_secondary',
        ],
        'instrumental_activities_of_daily' => [
            'telephone_uses_or_video_call',
            'telephone_uses_or_video_call_secondary',
            'money_manage_or_uses',
            'money_manage_or_uses_secondary',
            'personal_or_favorite_things_buy',
            'personal_or_favorite_things_buy_secondary',
            'transportation_uses',
            'transportation_uses_secondary',
            'doing_laundry_or_separate_dirty_cloth_or_dying',
            'doing_laundry_or_separate_dirty_cloth_or_dying_secondary',
            'cloth_fold_and_put_in_drawer',
            'cloth_fold_and_put_in_drawer_secondary',
            'working_at_home_or_toy_or_playground_clean_up',
            'working_at_home_or_toy_or_playground_clean_up_secondary',
            'cooking_food_or_eat_himself',
            'cooking_food_or_eat_himself_secondary',
            'cutting_vegetable_or_arrange_separately',
            'cutting_vegetable_or_arrange_separately_secondary',
        ],
        'environmental_safety_relative' => [
            'security',
            'security_secondary',
            'comfortable_arrangements',
            'comfortable_arrangements_secondary',
            'close_friend_or_relative',
            'close_friend_or_relative_secondary',
        ],
        'environmental_safety_step' => [
            'free_from_noise_and_obstruction',
            'free_from_noise_and_obstruction_secondary',
            'handles_on_both_sides_step',
            'handles_on_both_sides_step_secondary',
            'clearly_marked',
            'clearly_marked_secondary',
            'other_if_any',
            'other_if_any_secondary',
            'enter_the_details',
        ],
        'woke_up_in_the_morning' => [
            'wakeup_morning',
            'wakeup_morning_secondary',
            'wakeup_morning_time',
            'wakeup_morning_time_secondary',
            'bed_arrangement',
            'bed_arrangement_secondary',
            'bed_arrangement_time',
            'bed_arrangement_time_secondary',
            'teeth_brash',
            'teeth_brash_secondary',
            'teeth_brash_time',
            'teeth_brash_time_secondary',
            'hand_face_washing',
            'hand_face_washing_secondary',
            'hand_face_washing_time',
            'hand_face_washing_time_secondary',
            'changing_cloth',
            'changing_cloth_secondary',
            'changing_cloth_time',
            'changing_cloth_time_secondary',
            'hair_combing',
            'hair_combing_secondary',
            'hair_combing_time',
            'hair_combing_time_secondary',
            'snakes_cooking_eat_or_in_table',
            'snakes_cooking_eat_or_in_table_secondary',
            'snakes_cooking_eat_or_in_table_time',
            'snakes_cooking_eat_or_in_table_time_secondary',
            'cleaning_pleat_or_glass_or_put_in_wash_place',
            'cleaning_pleat_or_glass_or_put_in_wash_place_secondary',
            'cleaning_pleat_or_glass_or_put_in_wash_place_time',
            'cleaning_pleat_or_glass_or_put_in_wash_place_time_secondary',
            'clean_up_table',
            'clean_up_table_secondary',
            'clean_up_table_time',
            'clean_up_table_time_secondary',
        ],
        'reading_writing' => [
            'reading',
            'reading_secondary',
            'reading_time',
            'reading_time_secondary',
            'hand_writing',
            'hand_writing_secondary',
            'hand_writing_time',
            'hand_writing_time_secondary',
            'drawing_picture',
            'drawing_picture_secondary',
            'drawing_picture_time',
            'drawing_picture_time_secondary',
            'reading_paper',
            'reading_paper_secondary',
            'reading_paper_time',
            'reading_paper_time_secondary',
            'listening_song',
            'listening_song_secondary',
            'listening_song_time',
            'listening_song_time_secondary',
            'computer_practice',
            'computer_practice_secondary',
            'computer_practice_time',
            'computer_practice_time_secondary',
        ],
        'daily_work' => [
            'list_for_marketing',
            'list_for_marketing_secondary',
            'list_for_marketing_time',
            'list_for_marketing_time_secondary',
            'marketing_with_mother_and_father',
            'marketing_with_mother_and_father_secondary',
            'marketing_with_mother_and_father_time',
            'marketing_with_mother_and_father_time_secondary',
            'helping_mother_for_cutting_and_cooking_food',
            'helping_mother_for_cutting_and_cooking_food_secondary',
            'helping_mother_for_cutting_and_cooking_food_time',
            'helping_mother_for_cutting_and_cooking_food_time_secondary',
            'creating_menu_or_recognize_food_using_image',
            'creating_menu_or_recognize_food_using_image_secondary',
            'creating_menu_or_recognize_food_using_image_time',
            'creating_menu_or_recognize_food_using_image_time_secondary',
        ],
        'won_work' => [
            'washing_cloth_and_drying',
            'washing_cloth_and_drying_secondary',
            'washing_cloth_and_drying_time',
            'washing_cloth_and_drying_time_secondary',
            'clean_up_himself_room',
            'clean_up_himself_room_secondary',
            'clean_up_himself_room_time',
            'clean_up_himself_room_time_secondary',
            'folding_cloth',
            'folding_cloth_secondary',
            'folding_cloth_time',
            'folding_cloth_time_secondary',
            'tidy_wardrobe_or_cotton_drawer',
            'tidy_wardrobe_or_cotton_drawer_secondary',
            'tidy_wardrobe_or_cotton_drawer_time',
            'tidy_wardrobe_or_cotton_drawer_time_secondary',
            'iron_cloth',
            'iron_cloth_secondary',
            'iron_cloth_time',
            'iron_cloth_time_secondary',
            'cutting_nails',
            'cutting_nails_secondary',
            'cutting_nails_time',
            'cutting_nails_time_secondary',
            'hair_cutting',
            'hair_cutting_secondary',
            'hair_cutting_time',
            'hair_cutting_time_secondary',
            'shave',
            'shave_secondary',
            'shave_time',
            'shave_time_secondary',
        ],
        'lunch_time' => [
            'give_plate_glass_on_the_table_will_help',
            'give_plate_glass_on_the_table_will_help_secondary',
            'give_plate_glass_on_the_table_will_help_time',
            'give_plate_glass_on_the_table_will_help_time_secondary',
            'give_water_in_glass',
            'give_water_in_glass_secondary',
            'give_water_in_glass_time',
            'give_water_in_glass_time_secondary',
            'bring_food_from_the_kitchen_to_the_table',
            'bring_food_from_the_kitchen_to_the_table_secondary',
            'bring_food_from_the_kitchen_to_the_table_time',
            'bring_food_from_the_kitchen_to_the_table_time_secondary',
            'sit_on_the_table_or_mat_and_eat_with_everyone',
            'sit_on_the_table_or_mat_and_eat_with_everyone_secondary',
            'sit_on_the_table_or_mat_and_eat_with_everyone_time',
            'sit_on_the_table_or_mat_and_eat_with_everyone_time_secondary',
            'eat_with_your_own_hands_or_spoon',
            'eat_with_your_own_hands_or_spoon_secondary',
            'eat_with_your_own_hands_or_spoon_time',
            'eat_with_your_own_hands_or_spoon_time_secondary',
            'table_or_mat_will_help_clean',
            'table_or_mat_will_help_clean_secondary',
            'table_or_mat_will_help_clean_time',
            'table_or_mat_will_help_clean_time_secondary',
        ],
        'rest_time' => [
            'rest_in_bed',
            'rest_in_bed_secondary',
            'rest_in_bed_time',
            'rest_in_bed_time_secondary',
            'reading_story_book',
            'reading_story_book_secondary',
            'reading_story_book_time',
            'reading_story_book_time_secondary',
            'rest_time_listening_song',
            'rest_time_listening_song_secondary',
            'rest_time_listening_song_time',
            'rest_time_listening_song_time_secondary',
            'listening_time_secondary',
            'playing_video_game',
            'playing_video_game_secondary',
            'playing_video_game_time',
            'playing_video_game_time_secondary',
        ],
        'afternoon' => [
            'going_for_walk',
            'going_for_walk_secondary',
            'going_for_walk_time',
            'going_for_walk_time_secondary',
            'water_in_tub',
            'water_in_tub_secondary',
            'water_in_tub_time',
            'water_in_tub_time_secondary',
            'going_to_play_in_roof_or_playground',
            'going_to_play_in_roof_or_playground_secondary',
            'going_to_play_in_roof_or_playground_time',
            'going_to_play_in_roof_or_playground_time_secondary',
            'play_favorite_game',
            'play_favorite_game_secondary',
            'play_favorite_game_time',
            'play_favorite_game_time_secondary',
            'visiting_house_or_favorite_place_or_shopping',
            'visiting_house_or_favorite_place_or_shopping_secondary',
            'visiting_house_or_favorite_place_or_shopping_time',
            'visiting_house_or_favorite_place_or_shopping_time_secondary',
        ],
        'evening' => [
            'Make_sherbet_or_tea_or_snakes',
            'Make_sherbet_or_tea_or_snakes_secondary',
            'Make_sherbet_or_tea_or_snakes_time',
            'Make_sherbet_or_tea_or_snakes_time_secondary',
            'guest_reception',
            'guest_reception_secondary',
            'guest_reception_time',
            'guest_reception_time_secondary',
            'spending_time_with_brother_sister',
            'spending_time_with_brother_sister_secondary',
            'spending_time_with_brother_sister_time',
            'spending_time_with_brother_sister_time_secondary',
        ],

        'constructive_work' => [
            'reading_book_and_hand_writing',
            'reading_book_and_hand_writing_secondary',
            'reading_book_and_hand_writing_time',
            'reading_book_and_hand_writing_time_secondary',
            'constructive_game',
            'constructive_game_secondary',
            'constructive_game_time',
            'constructive_game_time_secondary',
            'constructive_work_computer_practice',
            'constructive_work_computer_practice_secondary',
            'constructive_work_computer_practice_time',
            'constructive_work_computer_practice_time_secondary',
            'home_work',
            'home_work_secondary',
            'home_work_time',
            'home_work_time_secondary',
            'packing_the_bag_for_the_next_day',
            'packing_the_bag_for_the_next_day_secondary',
            'packing_the_bag_for_the_next_day_time',
            'packing_the_bag_for_the_next_day_time_secondary',
            'watching_tv',
            'watching_tv_secondary',
            'watching_tv_time',
            'watching_tv_time_secondary',
            'dairy_writing',
            'dairy_writing_secondary',
            'dairy_writing_time',
            'dairy_writing_time_secondary',
        ],
        'dinner' => [
            'night_give_plate_glass_on_the_table_will_help',
            'night_give_plate_glass_on_the_table_will_help_secondary',
            'night_give_plate_glass_on_the_table_will_help_time',
            'night_give_plate_glass_on_the_table_will_help_time_secondary',
            'night_Give_water_in_glass',
            'night_Give_water_in_glass_secondary',
            'night_Give_water_in_glass_time',
            'night_Give_water_in_glass_time_secondary',
            'night_bring_food_from_the_kitchen_to_the_table',
            'night_bring_food_from_the_kitchen_to_the_table_secondary',
            'night_bring_food_from_the_kitchen_to_the_table_time',
            'night_bring_food_from_the_kitchen_to_the_table_time_secondary',
            'night_wash_hands_with_soap_before_and_after_eating',
            'night_sit_on_table_or_mat_and_eat_with_everyone',
            'night_sit_on_table_or_mat_and_eat_with_everyone_secondary',
            'night_sit_on_table_or_mat_and_eat_with_everyone_time',
            'night_sit_on_table_or_mat_and_eat_with_everyone_time_secondary',
            'night_eat_with_your',
            'night_eat_with_your_own_hands_or_spoon_secondary',
            'night_eat_with_your_own_hands_or_spoon_time',
            'night_eat_with_your_own_hands_or_spoon_time_secondary',
        ],
        'after_dinner' => [
            'night_eating_medicine',
            'night_eating_medicine_secondary',
            'night_eating_medicine_time',
            'night_eating_medicine_time_secondary',
            'night_teeth_brash',
            'night_teeth_brash_secondary',
            'night_teeth_brash_time',
            'night_teeth_brash_time_secondary',
            'night_changing_cloth',
            'night_changing_cloth_secondary',
            'night_changing_cloth_time',
            'night_changing_cloth_time_secondary',
            'put_to_bed',
            'put_to_bed_secondary',
            'put_to_bed_time',
            'put_to_bed_time_secondary',
            'hanging_mosquito_nets',
            'hanging_mosquito_nets_secondary',
            'hanging_mosquito_nets_time',
            'hanging_mosquito_nets_time_secondary',
            'turn_off_the_lights_and_go_to_bed',
            'turn_off_the_lights_and_go_to_bed_secondary',
            'turn_off_the_lights_and_go_to_bed_time',
            'turn_off_the_lights_and_go_to_bed_time_secondary',
        ],
        'signature' => [
            'special_educator_team',
            'special_educator_team_name',
            'guardian_img',
            'guardian_name',
            'note_if_any',
        ],
        'signature' => [
            'special_educator_team',
            'special_educator_team_name',
            'guardian_img',
            'guardian_name',
            'note_if_any',
        ],
        'trip_evaluation_signature' => [
            'signature_teacher',
            'signature_teacher_name_or_designation',
            'supervisor_signature',
            'supervisor_signature_name_or_designation',
        ],
    ];
}
